import DOMPurify from 'dompurify'

/**
 * Sanitize model-generated HTML before `dangerouslySetInnerHTML` or persistence.
 * Tight policy: no scripts, iframes, or inline event handlers.
 */
export function sanitizeCanvasHtmlFragment(html: string): string {
  return DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true },
    ALLOWED_TAGS: [
      'a',
      'article',
      'aside',
      'b',
      'blockquote',
      'br',
      'button',
      'caption',
      'cite',
      'code',
      'div',
      'em',
      'figcaption',
      'figure',
      'footer',
      'form',
      'h1',
      'h2',
      'h3',
      'h4',
      'header',
      'hr',
      'i',
      'img',
      'input',
      'label',
      'li',
      'main',
      'nav',
      'ol',
      'p',
      'pre',
      'section',
      'small',
      'span',
      'strong',
      'sub',
      'sup',
      'table',
      'tbody',
      'td',
      'textarea',
      'tfoot',
      'th',
      'thead',
      'tr',
      'u',
      'ul',
    ],
    ALLOWED_ATTR: [
      'alt',
      'aria-hidden',
      'aria-label',
      'class',
      'colspan',
      'disabled',
      'for',
      'href',
      'id',
      'maxlength',
      'minlength',
      'name',
      'placeholder',
      'readonly',
      'rel',
      'required',
      'role',
      'rowspan',
      'src',
      'target',
      'title',
      'type',
      'value',
    ],
    ALLOW_DATA_ATTR: false,
    FORBID_TAGS: ['script', 'style', 'iframe', 'object', 'embed', 'link', 'meta', 'base'],
  })
}
