/**
 * Labels for the sidebar “Components” explorer (counts are placeholders until wired to data).
 */
export const COMPONENT_EXPLORE_ITEMS: { label: string; count: number }[] = [
  { label: 'AI chats', count: 0 },
  { label: 'Alerts', count: 0 },
  { label: 'Avatars', count: 0 },
  { label: 'Badges', count: 0 },
  { label: 'Buttons', count: 0 },
  { label: 'Calendars', count: 0 },
  { label: 'Carousel', count: 0 },
  { label: 'Checkboxes', count: 0 },
  { label: 'Date pickers', count: 0 },
  { label: 'Dialogs', count: 0 },
  { label: 'Dropdowns', count: 0 },
  { label: 'Empty states', count: 0 },
  { label: 'Forms', count: 0 },
  { label: 'Icons', count: 0 },
  { label: 'Inputs', count: 0 },
  { label: 'Links', count: 0 },
  { label: 'Menus', count: 0 },
  { label: 'Notification', count: 0 },
  { label: 'Numbers', count: 0 },
  { label: 'Pagination', count: 0 },
  { label: 'Popover', count: 0 },
  { label: 'Radio groups', count: 0 },
  { label: 'Select', count: 0 },
  { label: 'Sidebar', count: 0 },
  { label: 'Sign in', count: 0 },
  { label: 'Sign up', count: 0 },
  { label: 'Sliders', count: 0 },
  { label: 'Spinners', count: 0 },
  { label: 'Tables', count: 0 },
  { label: 'Tabs', count: 0 },
  { label: 'Tags', count: 0 },
  { label: 'Text area', count: 0 },
  { label: 'Toast', count: 0 },
  { label: 'Toggles', count: 0 },
  { label: 'Tooltips', count: 0 },
]
